from app.db.tables.bank_data import bank_data_table
from app.db.tables.banks import banks_table
from app.db.tables.cashback_categories import cashback_categories_table
from app.db.tables.change_log import change_log_table
from app.db.tables.debts import debts_table
from app.db.tables.meetings import meetings_table
from app.db.tables.participant_cashback_categories import participant_cashback_categories_table
from app.db.tables.participants import participants_table
from app.db.tables.receipt_item_participants import receipt_item_participants_table
from app.db.tables.receipt_items import receipt_items_table
from app.db.tables.receipts import receipts_table
